apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  containers:
    - env:
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT-SECRET
          value: I9sXPyghLuMqRHkSGeTwKrlhlq5enE7z
      image: localhost:5000/sanotes-microservice-k8_api-gateway
      name: api-gateway
      ports:
        - containerPort: 8080
      resources: {}
  restartPolicy: OnFailure
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    io.kompose.service: api-gateway
status:
  loadBalancer: {}



