apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.service: notebook-service
  name: notebook-service
spec:
  containers:
    - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://db:5432/sanotes_notebookdb
      image: localhost:5000/sanotes-microservice-k8_notebook-service
      name: notebook-service
      ports:
        - containerPort: 8383
      resources: {}
  restartPolicy: OnFailure
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: notebook-service
  name: notebook-service
spec:
  type: NodePort
  ports:
    - name: "8383"
      port: 8383
      targetPort: 8383
      nodePort: 30083
  selector:
    io.kompose.service: notebook-service
status:
  loadBalancer: {}

