# note-service mongo database yaml files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-claim0
  name: mongo-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: notes
          image: mongo:latest
          name: sanotes-mongo-db
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mongo/data
              name: mongo-claim0
      restartPolicy: Always
      volumes:
        - name: mongo-claim0
          persistentVolumeClaim:
            claimName: mongo-claim0
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  type: NodePort
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
      nodePort: 30017
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}


---
# note-service postgres database yaml files

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-claim-note-service
  name: db-claim-note-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: db-note-service
  name: db-note-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-note-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: db-note-service
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: sanotes_notedb
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:alpine
          name: db-note-service
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-claim-note-service
      restartPolicy: Always
      volumes:
        - name: db-claim-note-service
          persistentVolumeClaim:
            claimName: db-claim-note-service
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: db-note-service
  name: db-note-service
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      nodePort: 31002
  selector:
    io.kompose.service: db-note-service
status:
  loadBalancer: {}


---
#note-service deployment and service yaml files
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.service: note-service
  name: note-service
spec:
  containers:
    - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://db-note-service:5432/sanotes_notedb
        - name: SPRING_DATA_MONGODB_DATABASE
          value: notes
        - name: SPRING_DATA_MONGODB_HOST
          value: mongo:27017
      image: localhost:5000/sanotes-microservice-k8_note-service
      name: note-service
      ports:
        - containerPort: 8282
      resources: {}
  restartPolicy: OnFailure
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: note-service
  name: note-service
spec:
  type: NodePort
  ports:
    - name: "8282"
      port: 8282
      targetPort: 8282
      nodePort: 30082
  selector:
    io.kompose.service: note-service
status:
  loadBalancer: {}

