apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.service: user-service
  name: user-service
spec:
  containers:
    - image: localhost:5000/sanotes-microservice-k8_user-service
      name: user-service
      ports:
        - containerPort: 8585
      resources: {}
  restartPolicy: OnFailure
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  type: NodePort
  ports:
    - name: "8585"
      port: 8585
      targetPort: 8585
      nodePort: 30085
  selector:
    io.kompose.service: user-service
status:
  loadBalancer: {}

